---
title: "Assignment 5 - Fundamentals of Machine Learning"
author: "Curtis Meister"
date: "2022-20-11"
output:
  pdf_document: default
  word_document: default
---

```{r}
library(cluster)
library(stats)
library(factoextra)
library(cluster)
library(fpc)
```

```{r}
rm(list=ls())
cereal <- read.csv("Cereals.csv", header=TRUE)
```

```{r}
head(cereal)
cereal <- na.omit(cereal)
row.names(cereal) <- cereal[,1]
cereal$name  = NULL
cereal <- subset(cereal, select = -c(1:2))
cereal <- scale(cereal)
head(cereal)
```

```{r}
d <- dist(cereal, method = "euclidean")
hc1 <- hclust(d, method = "complete")
SingleMethod <- hclust(d, method = "single")
HCfit <- hclust(d, method = "ward.D")
HCward <- hclust(d, method = "ward.D2")
```

```{r}
plot(hc1, cex = 0.6, hang = -1, ann = FALSE)
plot(HCfit, cex = 0.6, hang = -1, ann = FALSE)
plot(HCward, cex = 0.6, hang = -1, ann = FALSE)
HCsingle <- agnes(cereal, method = "single")
HCcomplete <- agnes(cereal, method = "complete")
HCaverage <- agnes(cereal, method = "average")
```

```{r}
print(HCsingle$ac)
print(HCcomplete$ac)
print(HCaverage$ac)
print(HCward$ac)
print(hc1)
print(HCfit)

plot(HCsingle)
plot(HCcomplete)
plot(HCaverage)
plot(HCward)

pltree(HCcomplete, cex = 0.6, hang = -1, main = "Agnes Dendogram")
df <- cereal
d <- dist(df, method = "euclidean")
hc_complete <- hclust(d, method = "complete")
```

```{r}
plot(hc_complete, cex = 0.6)
rect.hclust(HCcomplete, k = 6, border = 1:6)
set.seed(1)

k3 <- kmeans(cereal, centers = 3, nstart = 10)
k3$centers 
k3$size
k3$cluster[15]
str(k3)
fviz_cluster(k3, data = cereal)

set.seed(1)
fviz_nbclust(cereal, kmeans, method = "wss")
#we should have 6 clusters
```

```{r}
wss <- 0
for(i in 1:15) wss[i] <- sum(kmeans(cereal, centers = i)$withinss)
wss
plot(1:15, wss, type = "b", xlab="# of Clusters", ylab="Sum of squares")
fviz_nbclust(cereal, kmeans, method = "wss")

k6 <- kmeans(cereal, centers = 6)
k6clust <- k6$cluster
cereal_clust <- as.data.frame(cbind(k6$clust, cereal))
head(cereal_clust)
```


```{r}
hclust_stability <- clusterboot(cereal, clustermethod = hclustCBI, method = "ward.D", k=6)
hclust_stability
clusters = hclust_stability$results$partition
```

```{r}
cboot.hclust <- clusterboot(cereal, clustermethod = hclustCBI, method = "ward.D", k=6)
groups <- cboot.hclust$result$partition
cboot.hclust$bootmean
cboot.hclust$bootbrd
```

```{r}
d <- dist(cereal, method = "euclidean")
hc_single <- hclust(d, method = "single")
plot(hc_single, hang = -1, ann = FALSE)
hc_complete <- hclust(d, method = "complete")
plot(hc_complete, hang = -1, ann = FALSE)
dim(cereal)
```

```{r}
d <- dist(cereal[-c(1:3, 70:72),], method = "euclidean") 
hc_single <- hclust(d, method = "single")
plot(hc_single, hang = -1, ann = FALSE)
hc_complete <- hclust(d, method = "complete")
plot(hc_complete, hang = -1, ann = FALSE)
single <- cutree(hc_single, k = 6)
single
complete <- cutree(hc_complete, k = 6)
complete
```

```{r}
healthy_cereal <- read.csv("Cereals.csv", header=TRUE)
healthy_cereal <- na.omit(healthy_cereal)
rownames(healthy_cereal) <- healthy_cereal$name
healthy_cereal$name  = NULL
healthy_cereal <- subset(healthy_cereal, select = -c(1:3))
healthy_cereal <- scale(healthy_cereal)

fit <- kmeans(healthy_cereal, 6)
aggregate(healthy_cereal, by=list(fit$cluster), FUN=mean)
#Cluster 5 has the highest protein
#Cluster 6 has the lowest fat
#Cluster 5 has the lowest sodium
#Cluster 5 has the highest fiber
#Cluster 2 has the lowest carbohydrates
#Cluster 4 has the lowest sugar
#Cluster 5 has the highest potassium
#Cluster 1 has the most vitamins

#Based on the above, I would choose cluster 5. I disregarded negative numbers as you cannot have negative answers.
```
